name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Quartz
        uses: actions/checkout@v3
        with:
          repository: jackyzha0/quartz
          path: quartz
          fetch-depth: 1
      - name: Check out vault
        uses: actions/checkout@v3
        with:
          path: vault
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Build Quartz
        run: |
          rsync -a vault/.quartz/ quartz
          cd quartz
          npm ci
          npx quartz create -X symlink -s ../vault -l shortest
          npx quartz build

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
